# Generated by Django 4.0.4 on 2022-05-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardiologo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('estado_cardiologo', models.BooleanField(default=True, verbose_name='estado_cardiologo')),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('nombre_paciente', models.CharField(default=None, max_length=200, verbose_name='nombre_paciente')),
                ('dni_paciente', models.CharField(blank=True, default=None, max_length=100, verbose_name='dni_paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PreQuirurgico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('estado_prequirurgico', models.BooleanField(default=True, verbose_name='estado_prequirurgico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.paciente')),
            ],
        ),
    ]
