# Generated by Django 4.0.4 on 2022-05-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardiologo',
            options={'ordering': ['id'], 'verbose_name': 'cardiologo', 'verbose_name_plural': 'cardiologos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nombre_paciente'], 'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterModelOptions(
            name='prequirurgico',
            options={'ordering': ['id'], 'verbose_name': 'PreQuirurgico', 'verbose_name_plural': 'PreQuirurgicos'},
        ),
    ]
