# Generated by Django 4.0.4 on 2022-05-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_alter_cardiologo_options_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiologo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='prequirurgico',
            name='usuario',
        ),
    ]
